// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#include <stdlib.h>  // 包含abs()函数

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_top_nagivator1;
extern void ui_event_zhuyebtn1(lv_event_t * e);
extern lv_obj_t * ui_zhuyebtn1;
extern lv_obj_t * ui_WIFIbtn1;
extern void ui_event_soundbtn1(lv_event_t * e);
extern lv_obj_t * ui_soundbtn1;
extern lv_obj_t * ui_blueteethbtn1;
extern void ui_event_zhuye1(lv_event_t * e);
extern lv_obj_t * ui_zhuye1;
extern lv_obj_t * ui_sound1;
extern lv_obj_t * ui_WIFI1;
extern lv_obj_t * ui_blueteeth1;
extern void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_right;
extern lv_obj_t * ui_left;
extern lv_obj_t * ui_rightbtn;
extern lv_obj_t * ui_leftbtn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

