// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_top_nagivator4;
extern void ui_event_zhuyebtn4(lv_event_t * e);
extern lv_obj_t * ui_zhuyebtn4;
extern lv_obj_t * ui_WIFIbtn4;
extern void ui_event_soundbtn4(lv_event_t * e);
extern lv_obj_t * ui_soundbtn4;
extern lv_obj_t * ui_blueteethbtn4;
extern void ui_event_zhuye4(lv_event_t * e);
extern lv_obj_t * ui_zhuye4;
extern lv_obj_t * ui_sound4;
extern lv_obj_t * ui_WIFI4;
extern lv_obj_t * ui_blueteeth4;
extern void ui_event_Slider5(lv_event_t * e);
extern lv_obj_t * ui_Slider5;
extern lv_obj_t * ui_lababtn;
extern lv_obj_t * ui_turnleftbtn;
extern lv_obj_t * ui_turnrightbtn;
extern lv_obj_t * ui_warningbtn;
extern lv_obj_t * ui_turnleft;
extern lv_obj_t * ui_turnright;
extern lv_obj_t * ui_warning;
extern lv_obj_t * ui_laba;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

