// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_mainbg;
extern lv_obj_t * ui_top_nagivator2;
extern void ui_event_zhuyebtn2(lv_event_t * e);
extern lv_obj_t * ui_zhuyebtn2;
extern lv_obj_t * ui_WIFIbtn2;
extern void ui_event_soundbtn2(lv_event_t * e);
extern lv_obj_t * ui_soundbtn2;
extern lv_obj_t * ui_blueteethbtn2;
extern void ui_event_zhuye2(lv_event_t * e);
extern lv_obj_t * ui_zhuye2;
extern lv_obj_t * ui_sound2;
extern lv_obj_t * ui_WIFI2;
extern lv_obj_t * ui_blueteeth2;
extern void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_stop;
extern lv_obj_t * ui_back;
extern lv_obj_t * ui_forward;
extern lv_obj_t * ui_play;
extern void ui_event_stopbtn(lv_event_t * e);
extern lv_obj_t * ui_stopbtn;
extern void ui_event_playbtn(lv_event_t * e);
extern lv_obj_t * ui_playbtn;
extern lv_obj_t * ui_backbtn;
extern lv_obj_t * ui_forwardbtn;
extern lv_obj_t * ui_Dropdown1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

