// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_top_nagivator;
extern lv_obj_t * ui_leftblock;
extern lv_obj_t * ui_midblock;
extern lv_obj_t * ui_rightblock;
extern lv_obj_t * ui_zhuyebtn;
extern lv_obj_t * ui_musicbtn;
extern void ui_event_videobtn(lv_event_t * e);
extern lv_obj_t * ui_videobtn;
extern void ui_event_gamebtn(lv_event_t * e);
extern lv_obj_t * ui_gamebtn;
extern lv_obj_t * ui_nagivatorbtn;
extern lv_obj_t * ui_WIFIbtn;
extern void ui_event_soundbtn(lv_event_t * e);
extern lv_obj_t * ui_soundbtn;
extern lv_obj_t * ui_blueteethbtn;
extern void ui_event_zhuye(lv_event_t * e);
extern lv_obj_t * ui_zhuye;
extern lv_obj_t * ui_nagivation;
extern lv_obj_t * ui_music;
extern lv_obj_t * ui_video;
extern lv_obj_t * ui_Calendar1;
extern lv_obj_t * ui_game;
extern lv_obj_t * ui_sound;
extern lv_obj_t * ui_WIFI;
extern lv_obj_t * ui_blueteeth;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern void ui_event_picturebtn(lv_event_t * e);
extern lv_obj_t * ui_picturebtn;
extern lv_obj_t * ui_pic1;
extern lv_obj_t * ui_pic3;
extern lv_obj_t * ui_pic2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

