// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_homebg = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_startbtn = NULL;
lv_obj_t * ui_Welcome = NULL;
lv_obj_t * ui_Start = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Image20 = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        pangxie_Animation(ui_Image17, 0);
        fish2_Animation(ui_Image20, 0);
        fish1_Animation(ui_Image18, 0);
        zhangyu_Animation(ui_Image19, 0);
    }
}

void ui_event_startbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homebg = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_homebg, &ui_img_main_bg_png);
    lv_obj_set_width(ui_homebg, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_homebg, LV_SIZE_CONTENT);    /// 600
    lv_obj_set_align(ui_homebg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_homebg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 759);
    lv_obj_set_height(ui_Panel2, 367);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x535157), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startbtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_startbtn, 206);
    lv_obj_set_height(ui_startbtn, 50);
    lv_obj_set_x(ui_startbtn, 0);
    lv_obj_set_y(ui_startbtn, 81);
    lv_obj_set_align(ui_startbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_startbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_startbtn, lv_color_hex(0x2E303D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startbtn, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_startbtn, lv_color_hex(0xDAC8F8), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_startbtn, 180, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Welcome = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Welcome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Welcome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Welcome, 0);
    lv_obj_set_y(ui_Welcome, -80);
    lv_obj_set_align(ui_Welcome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Welcome, "Welcome to Wonderland!");
    lv_obj_clear_flag(ui_Welcome, LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags
    lv_obj_set_style_text_color(ui_Welcome, lv_color_hex(0xF0E6FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Welcome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Welcome, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Welcome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Welcome, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Start = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Start, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Start, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Start, 0);
    lv_obj_set_y(ui_Start, 80);
    lv_obj_set_align(ui_Start, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Start, "Start");
    lv_obj_set_style_text_color(ui_Start, lv_color_hex(0xE7DEF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Start, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image17, &ui_img_crab_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 189
    lv_obj_set_x(ui_Image17, -324);
    lv_obj_set_y(ui_Image17, -219);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image17, 100);

    ui_Image18 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image18, &ui_img_fish_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 156
    lv_obj_set_x(ui_Image18, -325);
    lv_obj_set_y(ui_Image18, 140);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image18, 100);

    ui_Image19 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image19, &ui_img_1616326166);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_Image19, 334);
    lv_obj_set_y(ui_Image19, -17);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image19, 100);

    ui_Image20 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image20, &ui_img_1935761100);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 186
    lv_obj_set_x(ui_Image20, -571);
    lv_obj_set_y(ui_Image20, -21);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image20, 100);

    lv_obj_add_event_cb(ui_startbtn, ui_event_startbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_homebg = NULL;
    ui_Panel2 = NULL;
    ui_startbtn = NULL;
    ui_Welcome = NULL;
    ui_Start = NULL;
    ui_Image17 = NULL;
    ui_Image18 = NULL;
    ui_Image19 = NULL;
    ui_Image20 = NULL;

}
