// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_top_nagivator3;
extern void ui_event_zhuyebtn3(lv_event_t * e);
extern lv_obj_t * ui_zhuyebtn3;
extern lv_obj_t * ui_WIFIbtn3;
extern void ui_event_soundbtn3(lv_event_t * e);
extern lv_obj_t * ui_soundbtn3;
extern lv_obj_t * ui_blueteethbtn3;
extern void ui_event_zhuye3(lv_event_t * e);
extern lv_obj_t * ui_zhuye3;
extern lv_obj_t * ui_sound3;
extern lv_obj_t * ui_WIFI3;
extern lv_obj_t * ui_blueteeth3;
extern void ui_event_Slider4(lv_event_t * e);
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Startgame;
extern lv_obj_t * ui_StartLabel;
extern lv_obj_t * ui_Pausegame;
extern lv_obj_t * ui_PauseLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

