// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#include "../ui.h"
#include "../src/picture.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_top_nagivator1 = NULL;
lv_obj_t * ui_zhuyebtn1 = NULL;
lv_obj_t * ui_WIFIbtn1 = NULL;
lv_obj_t * ui_soundbtn1 = NULL;
lv_obj_t * ui_blueteethbtn1 = NULL;
lv_obj_t * ui_zhuye1 = NULL;
lv_obj_t * ui_sound1 = NULL;
lv_obj_t * ui_WIFI1 = NULL;
lv_obj_t * ui_blueteeth1 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_right = NULL;
lv_obj_t * ui_left = NULL;
lv_obj_t * ui_rightbtn = NULL;
lv_obj_t * ui_leftbtn = NULL;
// event funtions
void ui_event_zhuyebtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_soundbtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_Slider2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Slider2, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_zhuye1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_zhuye1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Slider2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image8, &ui_img_bg2_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 600
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_top_nagivator1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_top_nagivator1, 1024);
    lv_obj_set_height(ui_top_nagivator1, 62);
    lv_obj_set_align(ui_top_nagivator1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_top_nagivator1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_top_nagivator1, lv_color_hex(0xACA49E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_top_nagivator1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuyebtn1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_zhuyebtn1, 50);
    lv_obj_set_height(ui_zhuyebtn1, 50);
    lv_obj_set_x(ui_zhuyebtn1, -477);
    lv_obj_set_y(ui_zhuyebtn1, -270);
    lv_obj_set_align(ui_zhuyebtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuyebtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_zhuyebtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_zhuyebtn1, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zhuyebtn1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIbtn1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_WIFIbtn1, 50);
    lv_obj_set_height(ui_WIFIbtn1, 50);
    lv_obj_set_x(ui_WIFIbtn1, 471);
    lv_obj_set_y(ui_WIFIbtn1, -270);
    lv_obj_set_align(ui_WIFIbtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIbtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WIFIbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WIFIbtn1, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFIbtn1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soundbtn1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_soundbtn1, 50);
    lv_obj_set_height(ui_soundbtn1, 50);
    lv_obj_set_x(ui_soundbtn1, 347);
    lv_obj_set_y(ui_soundbtn1, -269);
    lv_obj_set_align(ui_soundbtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_soundbtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_soundbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_soundbtn1, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundbtn1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blueteethbtn1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_blueteethbtn1, 50);
    lv_obj_set_height(ui_blueteethbtn1, 50);
    lv_obj_set_x(ui_blueteethbtn1, 410);
    lv_obj_set_y(ui_blueteethbtn1, -270);
    lv_obj_set_align(ui_blueteethbtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteethbtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_blueteethbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blueteethbtn1, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blueteethbtn1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuye1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_zhuye1, &ui_img_zhuye_png);
    lv_obj_set_width(ui_zhuye1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_zhuye1, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_zhuye1, -478);
    lv_obj_set_y(ui_zhuye1, -270);
    lv_obj_set_align(ui_zhuye1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuye1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zhuye1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_zhuye1, 55);

    ui_sound1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_sound1, &ui_img_yangshengqi_png);
    lv_obj_set_width(ui_sound1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_sound1, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_sound1, 347);
    lv_obj_set_y(ui_sound1, -270);
    lv_obj_set_align(ui_sound1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sound1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sound1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sound1, 55);

    ui_WIFI1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_WIFI1, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_WIFI1, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_WIFI1, 471);
    lv_obj_set_y(ui_WIFI1, -269);
    lv_obj_set_align(ui_WIFI1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI1, 55);

    ui_blueteeth1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_blueteeth1, &ui_img_lanya_png);
    lv_obj_set_width(ui_blueteeth1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_blueteeth1, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_blueteeth1, 408);
    lv_obj_set_y(ui_blueteeth1, -270);
    lv_obj_set_align(ui_blueteeth1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteeth1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_blueteeth1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_blueteeth1, 55);

    ui_Slider2 = lv_slider_create(ui_Screen3);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 269);
    lv_obj_set_height(ui_Slider2, 15);
    lv_obj_set_x(ui_Slider2, 0);
    lv_obj_set_y(ui_Slider2, -190);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x90D2EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x155C8F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x0F435E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_right = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_right, &ui_img_youjiantou_png);
    lv_obj_set_width(ui_right, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_right, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_right, 490);
    lv_obj_set_y(ui_right, 0);
    lv_obj_set_align(ui_right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_right, 100);

    ui_left = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_left, &ui_img_zuojiantou_png);
    lv_obj_set_width(ui_left, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_left, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_left, -490);
    lv_obj_set_y(ui_left, 0);
    lv_obj_set_align(ui_left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_left, 100);

    ui_rightbtn = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_rightbtn, 70);
    lv_obj_set_height(ui_rightbtn, 127);
    lv_obj_set_x(ui_rightbtn, 495);
    lv_obj_set_y(ui_rightbtn, 0);
    lv_obj_set_align(ui_rightbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rightbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rightbtn, lv_color_hex(0x523838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightbtn, 90, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftbtn = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_leftbtn, 70);
    lv_obj_set_height(ui_leftbtn, 127);
    lv_obj_set_x(ui_leftbtn, -495);
    lv_obj_set_y(ui_leftbtn, 0);
    lv_obj_set_align(ui_leftbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_leftbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftbtn, lv_color_hex(0x523838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftbtn, 90, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 初始化图库
    init_picture();

    lv_obj_add_event_cb(ui_zhuyebtn1, ui_event_zhuyebtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_soundbtn1, ui_event_soundbtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zhuye1, ui_event_zhuye1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);

}


void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Image8 = NULL;
    ui_top_nagivator1 = NULL;
    ui_zhuyebtn1 = NULL;
    ui_WIFIbtn1 = NULL;
    ui_soundbtn1 = NULL;
    ui_blueteethbtn1 = NULL;
    ui_zhuye1 = NULL;
    ui_sound1 = NULL;
    ui_WIFI1 = NULL;
    ui_blueteeth1 = NULL;
    ui_Slider2 = NULL;
    ui_right = NULL;
    ui_left = NULL;
    ui_rightbtn = NULL;
    ui_leftbtn = NULL;

}
