// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#include "../ui.h"
#include "../src/music.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_mainbg1 = NULL;
lv_obj_t * ui_top_nagivator5 = NULL;
lv_obj_t * ui_zhuyebtn5 = NULL;
lv_obj_t * ui_WIFIbtn5 = NULL;
lv_obj_t * ui_soundbtn5 = NULL;
lv_obj_t * ui_blueteethbtn5 = NULL;
lv_obj_t * ui_zhuye5 = NULL;
lv_obj_t * ui_sound5 = NULL;
lv_obj_t * ui_WIFI5 = NULL;
lv_obj_t * ui_blueteeth5 = NULL;
lv_obj_t * ui_Slider6 = NULL;
lv_obj_t * ui_stopmusic = NULL;
lv_obj_t * ui_playmusic = NULL;
lv_obj_t * ui_backmusic = NULL;
lv_obj_t * ui_forwardmusic = NULL;
lv_obj_t * ui_stopmusicbtn = NULL;
lv_obj_t * ui_playmusicbtn = NULL;
lv_obj_t * ui_backmusicbtn = NULL;
lv_obj_t * ui_forwardmusicbtn = NULL;
lv_obj_t * ui_Dropdownmusic = NULL;
// event funtions
void ui_event_zhuyebtn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_soundbtn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_Slider6, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Slider6, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_zhuye5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_zhuye5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        
        // 停止并清理音乐播放器
        stop_music();
        system("rm -f /tmp/mplayer_fifo");
        
        // 释放音乐列表内存
        if (music_list) {
            for (int i = 0; i < music_count; i++) {
                free(music_list[i]);
            }
            free(music_list);
            music_list = NULL;
            music_count = 0;
        }
    }
}




// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainbg1 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_mainbg1, &ui_img_bg2_png);
    lv_obj_set_width(ui_mainbg1, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_mainbg1, LV_SIZE_CONTENT);    /// 600
    lv_obj_set_align(ui_mainbg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainbg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainbg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_top_nagivator5 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_top_nagivator5, 1024);
    lv_obj_set_height(ui_top_nagivator5, 62);
    lv_obj_set_align(ui_top_nagivator5, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_top_nagivator5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_top_nagivator5, lv_color_hex(0xACA49E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_top_nagivator5, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuyebtn5 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_zhuyebtn5, 50);
    lv_obj_set_height(ui_zhuyebtn5, 50);
    lv_obj_set_x(ui_zhuyebtn5, -477);
    lv_obj_set_y(ui_zhuyebtn5, -270);
    lv_obj_set_align(ui_zhuyebtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuyebtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_zhuyebtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_zhuyebtn5, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zhuyebtn5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIbtn5 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_WIFIbtn5, 50);
    lv_obj_set_height(ui_WIFIbtn5, 50);
    lv_obj_set_x(ui_WIFIbtn5, 471);
    lv_obj_set_y(ui_WIFIbtn5, -270);
    lv_obj_set_align(ui_WIFIbtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIbtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WIFIbtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WIFIbtn5, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFIbtn5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soundbtn5 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_soundbtn5, 50);
    lv_obj_set_height(ui_soundbtn5, 50);
    lv_obj_set_x(ui_soundbtn5, 347);
    lv_obj_set_y(ui_soundbtn5, -269);
    lv_obj_set_align(ui_soundbtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_soundbtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_soundbtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_soundbtn5, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundbtn5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blueteethbtn5 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_blueteethbtn5, 50);
    lv_obj_set_height(ui_blueteethbtn5, 50);
    lv_obj_set_x(ui_blueteethbtn5, 410);
    lv_obj_set_y(ui_blueteethbtn5, -270);
    lv_obj_set_align(ui_blueteethbtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteethbtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_blueteethbtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blueteethbtn5, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blueteethbtn5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuye5 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_zhuye5, &ui_img_zhuye_png);
    lv_obj_set_width(ui_zhuye5, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_zhuye5, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_zhuye5, -478);
    lv_obj_set_y(ui_zhuye5, -270);
    lv_obj_set_align(ui_zhuye5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuye5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zhuye5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_zhuye5, 55);

    ui_sound5 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_sound5, &ui_img_yangshengqi_png);
    lv_obj_set_width(ui_sound5, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_sound5, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_sound5, 347);
    lv_obj_set_y(ui_sound5, -270);
    lv_obj_set_align(ui_sound5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sound5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sound5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sound5, 55);

    ui_WIFI5 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_WIFI5, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI5, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_WIFI5, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_WIFI5, 471);
    lv_obj_set_y(ui_WIFI5, -269);
    lv_obj_set_align(ui_WIFI5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI5, 55);

    ui_blueteeth5 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_blueteeth5, &ui_img_lanya_png);
    lv_obj_set_width(ui_blueteeth5, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_blueteeth5, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_blueteeth5, 408);
    lv_obj_set_y(ui_blueteeth5, -270);
    lv_obj_set_align(ui_blueteeth5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteeth5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_blueteeth5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_blueteeth5, 55);

    ui_Slider6 = lv_slider_create(ui_Screen7);
    lv_slider_set_value(ui_Slider6, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider6, 269);
    lv_obj_set_height(ui_Slider6, 15);
    lv_obj_set_x(ui_Slider6, 0);
    lv_obj_set_y(ui_Slider6, -190);
    lv_obj_set_align(ui_Slider6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Slider6, lv_color_hex(0x90D2EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider6, lv_color_hex(0x155C8F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider6, lv_color_hex(0x0F435E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider6, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_stopmusic = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_stopmusic, &ui_img_zanting_png);
    lv_obj_set_width(ui_stopmusic, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_stopmusic, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_stopmusic, 0);
    lv_obj_set_y(ui_stopmusic, 255);
    lv_obj_set_align(ui_stopmusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stopmusic, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_stopmusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_playmusic = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_playmusic, &ui_img_bofang_png);
    lv_obj_set_width(ui_playmusic, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_playmusic, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_playmusic, 2);
    lv_obj_set_y(ui_playmusic, 255);
    lv_obj_set_align(ui_playmusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playmusic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_playmusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backmusic = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_backmusic, &ui_img_660221470);
    lv_obj_set_width(ui_backmusic, LV_SIZE_CONTENT);   /// 246
    lv_obj_set_height(ui_backmusic, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_backmusic, -80);
    lv_obj_set_y(ui_backmusic, 255);
    lv_obj_set_align(ui_backmusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backmusic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backmusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_backmusic, 35);

    ui_forwardmusic = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_forwardmusic, &ui_img_899859302);
    lv_obj_set_width(ui_forwardmusic, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_forwardmusic, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_forwardmusic, 80);
    lv_obj_set_y(ui_forwardmusic, 255);
    lv_obj_set_align(ui_forwardmusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forwardmusic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_forwardmusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_forwardmusic, 35);

    ui_stopmusicbtn = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_stopmusicbtn, 50);
    lv_obj_set_height(ui_stopmusicbtn, 50);
    lv_obj_set_x(ui_stopmusicbtn, 0);
    lv_obj_set_y(ui_stopmusicbtn, 255);
    lv_obj_set_align(ui_stopmusicbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stopmusicbtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_stopmusicbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_stopmusicbtn, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stopmusicbtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playmusicbtn = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_playmusicbtn, 50);
    lv_obj_set_height(ui_playmusicbtn, 50);
    lv_obj_set_x(ui_playmusicbtn, 0);
    lv_obj_set_y(ui_playmusicbtn, 255);
    lv_obj_set_align(ui_playmusicbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playmusicbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_playmusicbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_playmusicbtn, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playmusicbtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backmusicbtn = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_backmusicbtn, 80);
    lv_obj_set_height(ui_backmusicbtn, 40);
    lv_obj_set_x(ui_backmusicbtn, -80);
    lv_obj_set_y(ui_backmusicbtn, 255);
    lv_obj_set_align(ui_backmusicbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backmusicbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backmusicbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backmusicbtn, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backmusicbtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forwardmusicbtn = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_forwardmusicbtn, 80);
    lv_obj_set_height(ui_forwardmusicbtn, 40);
    lv_obj_set_x(ui_forwardmusicbtn, 80);
    lv_obj_set_y(ui_forwardmusicbtn, 255);
    lv_obj_set_align(ui_forwardmusicbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forwardmusicbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_forwardmusicbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_forwardmusicbtn, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_forwardmusicbtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdownmusic = lv_dropdown_create(ui_Screen7);
    lv_dropdown_set_options(ui_Dropdownmusic, "Music 1\nMusic 2\nMusic 3");
    lv_obj_set_width(ui_Dropdownmusic, 200);
    lv_obj_set_height(ui_Dropdownmusic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdownmusic, -400);
    lv_obj_set_y(ui_Dropdownmusic, -210);
    lv_obj_set_align(ui_Dropdownmusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdownmusic, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdownmusic, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdownmusic, lv_color_hex(0xBCB9B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdownmusic, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Dropdownmusic, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_zhuyebtn5, ui_event_zhuyebtn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_soundbtn5, ui_event_soundbtn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zhuye5, ui_event_zhuye5, LV_EVENT_ALL, NULL);

    // 初始化音乐播放器
    init_music_player();
    
    // 设置音量滑块初始值
    lv_slider_set_value(ui_Slider6, current_volume, LV_ANIM_OFF);
    
    // 添加新的事件绑定
    lv_obj_add_event_cb(ui_Dropdownmusic, ui_event_Dropdownmusic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backmusicbtn, ui_event_backmusicbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_forwardmusicbtn, ui_event_forwardmusicbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider6, ui_event_Slider6_value_changed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_playmusicbtn, ui_event_playmusicbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stopmusicbtn, ui_event_stopmusicbtn, LV_EVENT_ALL, NULL);
    
    // // 如果音乐列表不为空，自动播放第一首
    // if (music_count > 0) {
    //     play_music(music_list[0]);
    // }
}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // 停止并清理音乐播放器
    stop_music();
    system("rm -f /tmp/mplayer_fifo");
    
    // 释放音乐列表内存
    if (music_list) {
        for (int i = 0; i < music_count; i++) {
            free(music_list[i]);
        }
        free(music_list);
        music_list = NULL;
        music_count = 0;
    }

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_mainbg1 = NULL;
    ui_top_nagivator5 = NULL;
    ui_zhuyebtn5 = NULL;
    ui_WIFIbtn5 = NULL;
    ui_soundbtn5 = NULL;
    ui_blueteethbtn5 = NULL;
    ui_zhuye5 = NULL;
    ui_sound5 = NULL;
    ui_WIFI5 = NULL;
    ui_blueteeth5 = NULL;
    ui_Slider6 = NULL;
    ui_stopmusic = NULL;
    ui_playmusic = NULL;
    ui_backmusic = NULL;
    ui_forwardmusic = NULL;
    ui_stopmusicbtn = NULL;
    ui_playmusicbtn = NULL;
    ui_backmusicbtn = NULL;
    ui_forwardmusicbtn = NULL;
    ui_Dropdownmusic = NULL;

}
