// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#include "../ui.h"
#include "../src/video.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_mainbg = NULL;
lv_obj_t * ui_top_nagivator2 = NULL;
lv_obj_t * ui_zhuyebtn2 = NULL;
lv_obj_t * ui_WIFIbtn2 = NULL;
lv_obj_t * ui_soundbtn2 = NULL;
lv_obj_t * ui_blueteethbtn2 = NULL;
lv_obj_t * ui_zhuye2 = NULL;
lv_obj_t * ui_sound2 = NULL;
lv_obj_t * ui_WIFI2 = NULL;
lv_obj_t * ui_blueteeth2 = NULL;
lv_obj_t * ui_Slider3 = NULL;
lv_obj_t * ui_stop = NULL;
lv_obj_t * ui_back = NULL;
lv_obj_t * ui_forward = NULL;
lv_obj_t * ui_play = NULL;
lv_obj_t * ui_stopbtn = NULL;
lv_obj_t * ui_playbtn = NULL;
lv_obj_t * ui_backbtn = NULL;
lv_obj_t * ui_forwardbtn = NULL;
lv_obj_t * ui_Dropdown1 = NULL;


// event funtions
void ui_event_zhuyebtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_Screen2_screen_init);
        
        // 停止视频播放
        video_stop();
    }
}

void ui_event_soundbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_Slider3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Slider3, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_zhuye2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_zhuye2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Slider3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}


// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainbg = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_mainbg, &ui_img_bg2_png);
    lv_obj_set_width(ui_mainbg, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_mainbg, LV_SIZE_CONTENT);    /// 600
    lv_obj_set_align(ui_mainbg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainbg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mainbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_top_nagivator2 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_top_nagivator2, 1024);
    lv_obj_set_height(ui_top_nagivator2, 62);
    lv_obj_set_align(ui_top_nagivator2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_top_nagivator2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_top_nagivator2, lv_color_hex(0xACA49E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_top_nagivator2, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuyebtn2 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_zhuyebtn2, 50);
    lv_obj_set_height(ui_zhuyebtn2, 50);
    lv_obj_set_x(ui_zhuyebtn2, -477);
    lv_obj_set_y(ui_zhuyebtn2, -270);
    lv_obj_set_align(ui_zhuyebtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuyebtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_zhuyebtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_zhuyebtn2, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zhuyebtn2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIbtn2 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_WIFIbtn2, 50);
    lv_obj_set_height(ui_WIFIbtn2, 50);
    lv_obj_set_x(ui_WIFIbtn2, 471);
    lv_obj_set_y(ui_WIFIbtn2, -270);
    lv_obj_set_align(ui_WIFIbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WIFIbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WIFIbtn2, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFIbtn2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soundbtn2 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_soundbtn2, 50);
    lv_obj_set_height(ui_soundbtn2, 50);
    lv_obj_set_x(ui_soundbtn2, 347);
    lv_obj_set_y(ui_soundbtn2, -269);
    lv_obj_set_align(ui_soundbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_soundbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_soundbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_soundbtn2, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundbtn2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blueteethbtn2 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_blueteethbtn2, 50);
    lv_obj_set_height(ui_blueteethbtn2, 50);
    lv_obj_set_x(ui_blueteethbtn2, 410);
    lv_obj_set_y(ui_blueteethbtn2, -270);
    lv_obj_set_align(ui_blueteethbtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteethbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_blueteethbtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blueteethbtn2, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blueteethbtn2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuye2 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_zhuye2, &ui_img_zhuye_png);
    lv_obj_set_width(ui_zhuye2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_zhuye2, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_zhuye2, -478);
    lv_obj_set_y(ui_zhuye2, -270);
    lv_obj_set_align(ui_zhuye2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuye2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zhuye2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_zhuye2, 55);

    ui_sound2 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_sound2, &ui_img_yangshengqi_png);
    lv_obj_set_width(ui_sound2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_sound2, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_sound2, 347);
    lv_obj_set_y(ui_sound2, -270);
    lv_obj_set_align(ui_sound2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sound2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sound2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sound2, 55);

    ui_WIFI2 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_WIFI2, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_WIFI2, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_WIFI2, 471);
    lv_obj_set_y(ui_WIFI2, -269);
    lv_obj_set_align(ui_WIFI2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI2, 55);

    ui_blueteeth2 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_blueteeth2, &ui_img_lanya_png);
    lv_obj_set_width(ui_blueteeth2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_blueteeth2, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_blueteeth2, 408);
    lv_obj_set_y(ui_blueteeth2, -270);
    lv_obj_set_align(ui_blueteeth2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteeth2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_blueteeth2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_blueteeth2, 55);

    ui_Slider3 = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_Slider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 269);
    lv_obj_set_height(ui_Slider3, 15);
    lv_obj_set_x(ui_Slider3, 0);
    lv_obj_set_y(ui_Slider3, -300);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x90D2EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x155C8F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x0F435E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_stop = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_stop, &ui_img_zanting_png);
    lv_obj_set_width(ui_stop, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_stop, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_stop, 0);
    lv_obj_set_y(ui_stop, 255);
    lv_obj_set_align(ui_stop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stop, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_stop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_stop, 255);

    ui_back = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_back, &ui_img_660221470);
    lv_obj_set_width(ui_back, LV_SIZE_CONTENT);   /// 246
    lv_obj_set_height(ui_back, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_back, -80);
    lv_obj_set_y(ui_back, 255);
    lv_obj_set_align(ui_back, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_back, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_back, 35);

    ui_forward = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_forward, &ui_img_899859302);
    lv_obj_set_width(ui_forward, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_forward, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_forward, 80);
    lv_obj_set_y(ui_forward, 255);
    lv_obj_set_align(ui_forward, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forward, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_forward, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_forward, 35);

    ui_play = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_play, &ui_img_bofang_png);
    lv_obj_set_width(ui_play, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_play, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_play, 0);
    lv_obj_set_y(ui_play, 255);
    lv_obj_set_align(ui_play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_play, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_play, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_play, 255);

    ui_stopbtn = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_stopbtn, 50);
    lv_obj_set_height(ui_stopbtn, 50);
    lv_obj_set_x(ui_stopbtn, 0);
    lv_obj_set_y(ui_stopbtn, 255);
    lv_obj_set_align(ui_stopbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stopbtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_stopbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_stopbtn, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stopbtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playbtn = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_playbtn, 50);
    lv_obj_set_height(ui_playbtn, 50);
    lv_obj_set_x(ui_playbtn, 0);
    lv_obj_set_y(ui_playbtn, 255);
    lv_obj_set_align(ui_playbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_playbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_playbtn, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_playbtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbtn = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_backbtn, 80);
    lv_obj_set_height(ui_backbtn, 40);
    lv_obj_set_x(ui_backbtn, -80);
    lv_obj_set_y(ui_backbtn, 255);
    lv_obj_set_align(ui_backbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_backbtn, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backbtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_forwardbtn = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_forwardbtn, 80);
    lv_obj_set_height(ui_forwardbtn, 40);
    lv_obj_set_x(ui_forwardbtn, 80);
    lv_obj_set_y(ui_forwardbtn, 255);
    lv_obj_set_align(ui_forwardbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_forwardbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_forwardbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_forwardbtn, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_forwardbtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_Screen4);
    lv_dropdown_set_options(ui_Dropdown1, "Video 1\nVideo 2\nVideo 3");
    lv_obj_set_width(ui_Dropdown1, 134);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, -442);
    lv_obj_set_y(ui_Dropdown1, -210);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown1, lv_color_hex(0xBCB9B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    

    // 加载视频文件到下拉菜单
    load_video_files();
    
    // 设置进度条为视频进度条
    lv_obj_add_event_cb(ui_Slider3, video_progress_handler, LV_EVENT_VALUE_CHANGED, NULL);
    
    // 设置下拉菜单事件处理
    lv_obj_add_event_cb(ui_Dropdown1, video_dropdown_handler, LV_EVENT_VALUE_CHANGED, NULL);


    lv_obj_add_event_cb(ui_zhuyebtn2, ui_event_zhuyebtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_soundbtn2, ui_event_soundbtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zhuye2, ui_event_zhuye2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider3, ui_event_Slider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stopbtn, ui_event_stopbtn, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(ui_playbtn, ui_event_playbtn, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(ui_backbtn, ui_event_backbtn, LV_EVENT_PRESSED, NULL);
    lv_obj_add_event_cb(ui_forwardbtn, ui_event_forwardbtn, LV_EVENT_PRESSED, NULL);

    // 设置进度条样式（与现有UI协调）
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x90D2EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x155C8F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x0F435E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
}

void ui_Screen4_screen_destroy(void)
{
    // 停止视频播放
    video_stop();    

    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_mainbg = NULL;
    ui_top_nagivator2 = NULL;
    ui_zhuyebtn2 = NULL;
    ui_WIFIbtn2 = NULL;
    ui_soundbtn2 = NULL;
    ui_blueteethbtn2 = NULL;
    ui_zhuye2 = NULL;
    ui_sound2 = NULL;
    ui_WIFI2 = NULL;
    ui_blueteeth2 = NULL;
    ui_Slider3 = NULL;
    ui_stop = NULL;
    ui_back = NULL;
    ui_forward = NULL;
    ui_play = NULL;
    ui_stopbtn = NULL;
    ui_playbtn = NULL;
    ui_backbtn = NULL;
    ui_forwardbtn = NULL;
    ui_Dropdown1 = NULL;

}
