// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#include "../ui.h"
#include "../src/gpio.h"


lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_top_nagivator4 = NULL;
lv_obj_t * ui_zhuyebtn4 = NULL;
lv_obj_t * ui_WIFIbtn4 = NULL;
lv_obj_t * ui_soundbtn4 = NULL;
lv_obj_t * ui_blueteethbtn4 = NULL;
lv_obj_t * ui_zhuye4 = NULL;
lv_obj_t * ui_sound4 = NULL;
lv_obj_t * ui_WIFI4 = NULL;
lv_obj_t * ui_blueteeth4 = NULL;
lv_obj_t * ui_Slider5 = NULL;
lv_obj_t * ui_lababtn = NULL;
lv_obj_t * ui_turnleftbtn = NULL;
lv_obj_t * ui_turnrightbtn = NULL;
lv_obj_t * ui_warningbtn = NULL;
lv_obj_t * ui_turnleft = NULL;
lv_obj_t * ui_turnright = NULL;
lv_obj_t * ui_warning = NULL;
lv_obj_t * ui_laba = NULL;
// event funtions
void ui_event_zhuyebtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_soundbtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_Slider5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Slider5, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_zhuye4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_zhuye4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Slider5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Slider5, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}






// build funtions


void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image2, &ui_img_bg2_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 600
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_top_nagivator4 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_top_nagivator4, 1024);
    lv_obj_set_height(ui_top_nagivator4, 62);
    lv_obj_set_align(ui_top_nagivator4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_top_nagivator4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_top_nagivator4, lv_color_hex(0xACA49E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_top_nagivator4, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuyebtn4 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_zhuyebtn4, 50);
    lv_obj_set_height(ui_zhuyebtn4, 50);
    lv_obj_set_x(ui_zhuyebtn4, -477);
    lv_obj_set_y(ui_zhuyebtn4, -270);
    lv_obj_set_align(ui_zhuyebtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuyebtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_zhuyebtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_zhuyebtn4, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zhuyebtn4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIbtn4 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_WIFIbtn4, 50);
    lv_obj_set_height(ui_WIFIbtn4, 50);
    lv_obj_set_x(ui_WIFIbtn4, 471);
    lv_obj_set_y(ui_WIFIbtn4, -270);
    lv_obj_set_align(ui_WIFIbtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIbtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WIFIbtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WIFIbtn4, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFIbtn4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soundbtn4 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_soundbtn4, 50);
    lv_obj_set_height(ui_soundbtn4, 50);
    lv_obj_set_x(ui_soundbtn4, 347);
    lv_obj_set_y(ui_soundbtn4, -269);
    lv_obj_set_align(ui_soundbtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_soundbtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_soundbtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_soundbtn4, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundbtn4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blueteethbtn4 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_blueteethbtn4, 50);
    lv_obj_set_height(ui_blueteethbtn4, 50);
    lv_obj_set_x(ui_blueteethbtn4, 410);
    lv_obj_set_y(ui_blueteethbtn4, -270);
    lv_obj_set_align(ui_blueteethbtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteethbtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_blueteethbtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blueteethbtn4, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blueteethbtn4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuye4 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_zhuye4, &ui_img_zhuye_png);
    lv_obj_set_width(ui_zhuye4, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_zhuye4, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_zhuye4, -478);
    lv_obj_set_y(ui_zhuye4, -270);
    lv_obj_set_align(ui_zhuye4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuye4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zhuye4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_zhuye4, 55);

    ui_sound4 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_sound4, &ui_img_yangshengqi_png);
    lv_obj_set_width(ui_sound4, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_sound4, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_sound4, 347);
    lv_obj_set_y(ui_sound4, -270);
    lv_obj_set_align(ui_sound4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sound4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sound4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sound4, 55);

    ui_WIFI4 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_WIFI4, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI4, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_WIFI4, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_WIFI4, 471);
    lv_obj_set_y(ui_WIFI4, -269);
    lv_obj_set_align(ui_WIFI4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI4, 55);

    ui_blueteeth4 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_blueteeth4, &ui_img_lanya_png);
    lv_obj_set_width(ui_blueteeth4, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_blueteeth4, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_blueteeth4, 408);
    lv_obj_set_y(ui_blueteeth4, -270);
    lv_obj_set_align(ui_blueteeth4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteeth4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_blueteeth4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_blueteeth4, 55);

    ui_Slider5 = lv_slider_create(ui_Screen6);
    lv_slider_set_value(ui_Slider5, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider5, 269);
    lv_obj_set_height(ui_Slider5, 15);
    lv_obj_set_x(ui_Slider5, 0);
    lv_obj_set_y(ui_Slider5, -190);
    lv_obj_set_align(ui_Slider5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Slider5, lv_color_hex(0x90D2EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider5, lv_color_hex(0x155C8F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider5, lv_color_hex(0x0F435E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lababtn = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_lababtn, 120);
    lv_obj_set_height(ui_lababtn, 120);
    lv_obj_set_align(ui_lababtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lababtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lababtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_lababtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lababtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_lababtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_lababtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turnleftbtn = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_turnleftbtn, 150);
    lv_obj_set_height(ui_turnleftbtn, 100);
    lv_obj_set_x(ui_turnleftbtn, -400);
    lv_obj_set_y(ui_turnleftbtn, -13);
    lv_obj_set_align(ui_turnleftbtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_turnleftbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_turnleftbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_turnleftbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_turnleftbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_turnleftbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_turnleftbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turnrightbtn = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_turnrightbtn, 150);
    lv_obj_set_height(ui_turnrightbtn, 100);
    lv_obj_set_x(ui_turnrightbtn, 400);
    lv_obj_set_y(ui_turnrightbtn, -13);
    lv_obj_set_align(ui_turnrightbtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_turnrightbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_turnrightbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_turnrightbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_turnrightbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_turnrightbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_turnrightbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_warningbtn = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_warningbtn, 100);
    lv_obj_set_height(ui_warningbtn, 90);
    lv_obj_set_x(ui_warningbtn, 0);
    lv_obj_set_y(ui_warningbtn, -20);
    lv_obj_set_align(ui_warningbtn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_warningbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_warningbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_warningbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_warningbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_warningbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_warningbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turnleft = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_turnleft, &ui_img_turnleft_png);
    lv_obj_set_width(ui_turnleft, LV_SIZE_CONTENT);   /// 185
    lv_obj_set_height(ui_turnleft, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_turnleft, -400);
    lv_obj_set_y(ui_turnleft, 0);
    lv_obj_set_align(ui_turnleft, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_turnleft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_turnleft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_turnleft, 200);

    ui_turnright = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_turnright, &ui_img_turnright_png);
    lv_obj_set_width(ui_turnright, LV_SIZE_CONTENT);   /// 184
    lv_obj_set_height(ui_turnright, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_turnright, 400);
    lv_obj_set_y(ui_turnright, 0);
    lv_obj_set_align(ui_turnright, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_turnright, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_turnright, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_turnright, 200);

    ui_warning = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_warning, &ui_img_shuangshan_png);
    lv_obj_set_width(ui_warning, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_warning, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_align(ui_warning, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_warning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_warning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_laba = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_laba, &ui_img_laba_png);
    lv_obj_set_width(ui_laba, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_laba, LV_SIZE_CONTENT);    /// 300
    lv_obj_set_align(ui_laba, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_laba, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_laba, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_zhuyebtn4, ui_event_zhuyebtn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_soundbtn4, ui_event_soundbtn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zhuye4, ui_event_zhuye4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider5, ui_event_Slider5, LV_EVENT_ALL, NULL);

    // 添加新的事件绑定
    lv_obj_add_event_cb(ui_turnleftbtn, ui_event_turnleftbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_turnrightbtn, ui_event_turnrightbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_warningbtn, ui_event_warningbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lababtn, ui_event_lababtn, LV_EVENT_ALL, NULL);

    // 重置所有UI元素的状态
    lv_obj_set_style_img_recolor(ui_turnleft, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_img_recolor_opa(ui_turnleft, LV_OPA_0, 0);
    lv_obj_set_style_img_recolor(ui_turnright, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_img_recolor_opa(ui_turnright, LV_OPA_0, 0);
    lv_obj_set_style_img_recolor(ui_warning, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_img_recolor_opa(ui_warning, LV_OPA_0, 0);
    lv_obj_set_style_img_recolor(ui_laba, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_img_recolor_opa(ui_laba, LV_OPA_0, 0);

    // 初始化GPIO引脚
    init_gpio();

    // 创建闪烁定时器
    static lv_timer_t *blink_timer = NULL;
    if (!blink_timer) {
        blink_timer = lv_timer_create(blink_timer_callback, 500, NULL); // 500ms闪烁间隔
        lv_timer_set_repeat_count(blink_timer, -1); // 无限重复
    }
}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // 取消导出GPIO
    system(UNEXPORT_GPIO(120));
    system(UNEXPORT_GPIO(121));
    system(UNEXPORT_GPIO(123));
    system(UNEXPORT_GPIO(124));
    system(UNEXPORT_GPIO(111));

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Image2 = NULL;
    ui_top_nagivator4 = NULL;
    ui_zhuyebtn4 = NULL;
    ui_WIFIbtn4 = NULL;
    ui_soundbtn4 = NULL;
    ui_blueteethbtn4 = NULL;
    ui_zhuye4 = NULL;
    ui_sound4 = NULL;
    ui_WIFI4 = NULL;
    ui_blueteeth4 = NULL;
    ui_Slider5 = NULL;
    ui_lababtn = NULL;
    ui_turnleftbtn = NULL;
    ui_turnrightbtn = NULL;
    ui_warningbtn = NULL;
    ui_turnleft = NULL;
    ui_turnright = NULL;
    ui_warning = NULL;
    ui_laba = NULL;

}
