// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#include "../ui.h"
#include "../src/timer.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_top_nagivator = NULL;
lv_obj_t * ui_leftblock = NULL;
lv_obj_t * ui_midblock = NULL;
lv_obj_t * ui_rightblock = NULL;
lv_obj_t * ui_zhuyebtn = NULL;
lv_obj_t * ui_musicbtn = NULL;
lv_obj_t * ui_videobtn = NULL;
lv_obj_t * ui_gamebtn = NULL;
lv_obj_t * ui_nagivatorbtn = NULL;
lv_obj_t * ui_WIFIbtn = NULL;
lv_obj_t * ui_soundbtn = NULL;
lv_obj_t * ui_blueteethbtn = NULL;
lv_obj_t * ui_zhuye = NULL;
lv_obj_t * ui_nagivation = NULL;
lv_obj_t * ui_music = NULL;
lv_obj_t * ui_video = NULL;
lv_obj_t * ui_Calendar1 = NULL;
lv_obj_t * ui_game = NULL;
lv_obj_t * ui_sound = NULL;
lv_obj_t * ui_WIFI = NULL;
lv_obj_t * ui_blueteeth = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_picturebtn = NULL;
lv_obj_t * ui_pic1 = NULL;
lv_obj_t * ui_pic3 = NULL;
lv_obj_t * ui_pic2 = NULL;

// event funtions
void ui_event_videobtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_gamebtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_soundbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_Slider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Slider1, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_zhuye(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_zhuye, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Slider1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_picturebtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_nagivatorbtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_musicbtn(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_Screen7_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image3, &ui_img_main_bg_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1024
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 600
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_top_nagivator = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_top_nagivator, 1024);
    lv_obj_set_height(ui_top_nagivator, 62);
    lv_obj_set_align(ui_top_nagivator, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_top_nagivator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_top_nagivator, lv_color_hex(0xACA49E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_top_nagivator, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 初始化实时时间
    init_timer();

    ui_leftblock = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_leftblock, 250);
    lv_obj_set_height(ui_leftblock, 250);
    lv_obj_set_x(ui_leftblock, -320);
    lv_obj_set_y(ui_leftblock, 0);
    lv_obj_set_align(ui_leftblock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftblock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftblock, lv_color_hex(0x8D8582), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftblock, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_midblock = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_midblock, 350);
    lv_obj_set_height(ui_midblock, 350);
    lv_obj_set_align(ui_midblock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_midblock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_midblock, lv_color_hex(0x8F8784), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_midblock, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightblock = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_rightblock, 250);
    lv_obj_set_height(ui_rightblock, 250);
    lv_obj_set_x(ui_rightblock, 320);
    lv_obj_set_y(ui_rightblock, 0);
    lv_obj_set_align(ui_rightblock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightblock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rightblock, lv_color_hex(0x8F8883), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightblock, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuyebtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_zhuyebtn, 50);
    lv_obj_set_height(ui_zhuyebtn, 50);
    lv_obj_set_x(ui_zhuyebtn, -477);
    lv_obj_set_y(ui_zhuyebtn, -270);
    lv_obj_set_align(ui_zhuyebtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuyebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_zhuyebtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_zhuyebtn, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zhuyebtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_musicbtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_musicbtn, 90);
    lv_obj_set_height(ui_musicbtn, 90);
    lv_obj_set_x(ui_musicbtn, -265);
    lv_obj_set_y(ui_musicbtn, 60);
    lv_obj_set_align(ui_musicbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_musicbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_musicbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_musicbtn, lv_color_hex(0xEBDAC7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_musicbtn, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_videobtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_videobtn, 90);
    lv_obj_set_height(ui_videobtn, 90);
    lv_obj_set_x(ui_videobtn, -370);
    lv_obj_set_y(ui_videobtn, 60);
    lv_obj_set_align(ui_videobtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_videobtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_videobtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_videobtn, lv_color_hex(0xEBDAC7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_videobtn, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gamebtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_gamebtn, 90);
    lv_obj_set_height(ui_gamebtn, 90);
    lv_obj_set_x(ui_gamebtn, -370);
    lv_obj_set_y(ui_gamebtn, -60);
    lv_obj_set_align(ui_gamebtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gamebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_gamebtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_gamebtn, lv_color_hex(0xEBDAC7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gamebtn, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nagivatorbtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_nagivatorbtn, 90);
    lv_obj_set_height(ui_nagivatorbtn, 90);
    lv_obj_set_x(ui_nagivatorbtn, -265);
    lv_obj_set_y(ui_nagivatorbtn, -60);
    lv_obj_set_align(ui_nagivatorbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nagivatorbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_nagivatorbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_nagivatorbtn, lv_color_hex(0xEBDAC7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nagivatorbtn, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIbtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_WIFIbtn, 50);
    lv_obj_set_height(ui_WIFIbtn, 50);
    lv_obj_set_x(ui_WIFIbtn, 471);
    lv_obj_set_y(ui_WIFIbtn, -270);
    lv_obj_set_align(ui_WIFIbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WIFIbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WIFIbtn, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFIbtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soundbtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_soundbtn, 50);
    lv_obj_set_height(ui_soundbtn, 50);
    lv_obj_set_x(ui_soundbtn, 347);
    lv_obj_set_y(ui_soundbtn, -269);
    lv_obj_set_align(ui_soundbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_soundbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_soundbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_soundbtn, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundbtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blueteethbtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_blueteethbtn, 50);
    lv_obj_set_height(ui_blueteethbtn, 50);
    lv_obj_set_x(ui_blueteethbtn, 410);
    lv_obj_set_y(ui_blueteethbtn, -270);
    lv_obj_set_align(ui_blueteethbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteethbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_blueteethbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blueteethbtn, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blueteethbtn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuye = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_zhuye, &ui_img_zhuye_png);
    lv_obj_set_width(ui_zhuye, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_zhuye, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_zhuye, -478);
    lv_obj_set_y(ui_zhuye, -270);
    lv_obj_set_align(ui_zhuye, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuye, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_zhuye, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_zhuye, 55);

    ui_nagivation = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_nagivation, &ui_img_daohang_png);
    lv_obj_set_width(ui_nagivation, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_nagivation, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_nagivation, -268);
    lv_obj_set_y(ui_nagivation, -55);
    lv_obj_set_align(ui_nagivation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nagivation, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_nagivation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_nagivation, 90);

    ui_music = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_music, &ui_img_yinle_png);
    lv_obj_set_width(ui_music, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_music, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_music, -265);
    lv_obj_set_y(ui_music, 60);
    lv_obj_set_align(ui_music, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_music, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_music, 90);

    ui_video = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_video, &ui_img_shipin_png);
    lv_obj_set_width(ui_video, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_video, LV_SIZE_CONTENT);    /// 188
    lv_obj_set_x(ui_video, -370);
    lv_obj_set_y(ui_video, 60);
    lv_obj_set_align(ui_video, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_video, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_video, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_video, 90);

    // 初始化日历
    init_calendar();

    ui_game = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_game, &ui_img_game_png);
    lv_obj_set_width(ui_game, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_game, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_game, -370);
    lv_obj_set_y(ui_game, -60);
    lv_obj_set_align(ui_game, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_game, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_game, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_game, 90);

    ui_sound = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_sound, &ui_img_yangshengqi_png);
    lv_obj_set_width(ui_sound, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_sound, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_sound, 347);
    lv_obj_set_y(ui_sound, -270);
    lv_obj_set_align(ui_sound, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sound, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sound, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_sound, 55);

    ui_WIFI = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_WIFI, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_WIFI, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_WIFI, 471);
    lv_obj_set_y(ui_WIFI, -269);
    lv_obj_set_align(ui_WIFI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WIFI, 55);

    ui_blueteeth = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_blueteeth, &ui_img_lanya_png);
    lv_obj_set_width(ui_blueteeth, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_blueteeth, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_blueteeth, 408);
    lv_obj_set_y(ui_blueteeth, -270);
    lv_obj_set_align(ui_blueteeth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteeth, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_blueteeth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_blueteeth, 55);

    ui_Slider1 = lv_slider_create(ui_Screen2);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 269);
    lv_obj_set_height(ui_Slider1, 15);
    lv_obj_set_x(ui_Slider1, 0);
    lv_obj_set_y(ui_Slider1, -190);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x90D2EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x155C8F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x0F435E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_picturebtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_picturebtn, 200);
    lv_obj_set_height(ui_picturebtn, 200);
    lv_obj_set_x(ui_picturebtn, 320);
    lv_obj_set_y(ui_picturebtn, 0);
    lv_obj_set_align(ui_picturebtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_picturebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_picturebtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_picturebtn, lv_color_hex(0xA69B93), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_picturebtn, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pic1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_pic1, &ui_img_pic1_png);
    lv_obj_set_width(ui_pic1, LV_SIZE_CONTENT);   /// 250
    lv_obj_set_height(ui_pic1, LV_SIZE_CONTENT);    /// 250
    lv_obj_set_x(ui_pic1, 372);
    lv_obj_set_y(ui_pic1, -17);
    lv_obj_set_align(ui_pic1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pic1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pic1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_pic1, 70);
    lv_obj_set_style_shadow_color(ui_pic1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pic1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pic1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pic1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pic3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_pic3, &ui_img_pic2_png);
    lv_obj_set_width(ui_pic3, LV_SIZE_CONTENT);   /// 250
    lv_obj_set_height(ui_pic3, LV_SIZE_CONTENT);    /// 250
    lv_obj_set_x(ui_pic3, 275);
    lv_obj_set_y(ui_pic3, -38);
    lv_obj_set_align(ui_pic3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pic3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pic3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_pic3, 80);
    lv_obj_set_style_shadow_color(ui_pic3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pic3, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pic3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pic3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pic2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_pic2, &ui_img_pic3_png);
    lv_obj_set_width(ui_pic2, LV_SIZE_CONTENT);   /// 250
    lv_obj_set_height(ui_pic2, LV_SIZE_CONTENT);    /// 250
    lv_obj_set_x(ui_pic2, 315);
    lv_obj_set_y(ui_pic2, 41);
    lv_obj_set_align(ui_pic2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pic2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pic2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_pic2, 90);
    lv_obj_set_style_shadow_color(ui_pic2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pic2, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pic2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pic2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_videobtn, ui_event_videobtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_gamebtn, ui_event_gamebtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_soundbtn, ui_event_soundbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zhuye, ui_event_zhuye, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_picturebtn, ui_event_picturebtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_nagivatorbtn, ui_event_nagivatorbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_musicbtn, ui_event_musicbtn, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image3 = NULL;
    ui_top_nagivator = NULL;
    ui_leftblock = NULL;
    ui_midblock = NULL;
    ui_rightblock = NULL;
    ui_zhuyebtn = NULL;
    ui_musicbtn = NULL;
    ui_videobtn = NULL;
    ui_gamebtn = NULL;
    ui_nagivatorbtn = NULL;
    ui_WIFIbtn = NULL;
    ui_soundbtn = NULL;
    ui_blueteethbtn = NULL;
    ui_zhuye = NULL;
    ui_nagivation = NULL;
    ui_music = NULL;
    ui_video = NULL;
    ui_Calendar1 = NULL;
    ui_game = NULL;
    ui_sound = NULL;
    ui_WIFI = NULL;
    ui_blueteeth = NULL;
    ui_Slider1 = NULL;
    ui_picturebtn = NULL;
    ui_pic1 = NULL;
    ui_pic3 = NULL;
    ui_pic2 = NULL;

}
