// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#include "../ui.h"
#include "../src/snack.h"


lv_obj_t *ui_Screen5 = NULL;
lv_obj_t *ui_Image1 = NULL;
lv_obj_t *ui_top_nagivator3 = NULL;
lv_obj_t *ui_zhuyebtn3 = NULL;
lv_obj_t *ui_WIFIbtn3 = NULL;
lv_obj_t *ui_soundbtn3 = NULL;
lv_obj_t *ui_blueteethbtn3 = NULL;
lv_obj_t *ui_zhuye3 = NULL;
lv_obj_t *ui_sound3 = NULL;
lv_obj_t *ui_WIFI3 = NULL;
lv_obj_t *ui_blueteeth3 = NULL;
lv_obj_t *ui_Slider4 = NULL;
lv_obj_t *ui_Startgame = NULL;
lv_obj_t *ui_StartLabel = NULL;
lv_obj_t *ui_Pausegame = NULL;
lv_obj_t *ui_PauseLabel = NULL;


// event funtions
void ui_event_zhuyebtn3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 800, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_soundbtn3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_PRESSED)
    {
        _ui_flag_modify(ui_Slider4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Slider4, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_zhuye3(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_flag_modify(ui_zhuye3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Slider4(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_DEFOCUSED)
    {
        _ui_flag_modify(ui_Slider4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions


void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image1 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image1, &ui_img_bg2_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);  /// 1024
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT); /// 600
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_top_nagivator3 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_top_nagivator3, 1024);
    lv_obj_set_height(ui_top_nagivator3, 62);
    lv_obj_set_align(ui_top_nagivator3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_top_nagivator3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_top_nagivator3, lv_color_hex(0xACA49E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_top_nagivator3, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuyebtn3 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_zhuyebtn3, 50);
    lv_obj_set_height(ui_zhuyebtn3, 50);
    lv_obj_set_x(ui_zhuyebtn3, -477);
    lv_obj_set_y(ui_zhuyebtn3, -270);
    lv_obj_set_align(ui_zhuyebtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuyebtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_zhuyebtn3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_zhuyebtn3, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_zhuyebtn3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIbtn3 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_WIFIbtn3, 50);
    lv_obj_set_height(ui_WIFIbtn3, 50);
    lv_obj_set_x(ui_WIFIbtn3, 471);
    lv_obj_set_y(ui_WIFIbtn3, -270);
    lv_obj_set_align(ui_WIFIbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIbtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_WIFIbtn3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_WIFIbtn3, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFIbtn3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soundbtn3 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_soundbtn3, 50);
    lv_obj_set_height(ui_soundbtn3, 50);
    lv_obj_set_x(ui_soundbtn3, 347);
    lv_obj_set_y(ui_soundbtn3, -269);
    lv_obj_set_align(ui_soundbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_soundbtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_soundbtn3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_soundbtn3, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_soundbtn3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blueteethbtn3 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_blueteethbtn3, 50);
    lv_obj_set_height(ui_blueteethbtn3, 50);
    lv_obj_set_x(ui_blueteethbtn3, 410);
    lv_obj_set_y(ui_blueteethbtn3, -270);
    lv_obj_set_align(ui_blueteethbtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteethbtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_blueteethbtn3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_blueteethbtn3, lv_color_hex(0xBDB3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blueteethbtn3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhuye3 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_zhuye3, &ui_img_zhuye_png);
    lv_obj_set_width(ui_zhuye3, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_zhuye3, LV_SIZE_CONTENT); /// 200
    lv_obj_set_x(ui_zhuye3, -478);
    lv_obj_set_y(ui_zhuye3, -270);
    lv_obj_set_align(ui_zhuye3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_zhuye3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_zhuye3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_zhuye3, 55);

    ui_sound3 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_sound3, &ui_img_yangshengqi_png);
    lv_obj_set_width(ui_sound3, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_sound3, LV_SIZE_CONTENT); /// 200
    lv_obj_set_x(ui_sound3, 347);
    lv_obj_set_y(ui_sound3, -270);
    lv_obj_set_align(ui_sound3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sound3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_sound3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_sound3, 55);

    ui_WIFI3 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_WIFI3, &ui_img_wifi_png);
    lv_obj_set_width(ui_WIFI3, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_WIFI3, LV_SIZE_CONTENT); /// 200
    lv_obj_set_x(ui_WIFI3, 471);
    lv_obj_set_y(ui_WIFI3, -269);
    lv_obj_set_align(ui_WIFI3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_WIFI3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_WIFI3, 55);

    ui_blueteeth3 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_blueteeth3, &ui_img_lanya_png);
    lv_obj_set_width(ui_blueteeth3, LV_SIZE_CONTENT);  /// 200
    lv_obj_set_height(ui_blueteeth3, LV_SIZE_CONTENT); /// 200
    lv_obj_set_x(ui_blueteeth3, 408);
    lv_obj_set_y(ui_blueteeth3, -270);
    lv_obj_set_align(ui_blueteeth3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blueteeth3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_blueteeth3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_blueteeth3, 55);

    ui_Slider4 = lv_slider_create(ui_Screen5);
    lv_slider_set_value(ui_Slider4, 0, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 269);
    lv_obj_set_height(ui_Slider4, 15);
    lv_obj_set_x(ui_Slider4, 0);
    lv_obj_set_y(ui_Slider4, -190);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider4, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0x90D2EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0x155C8F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0x0F435E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Startgame = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Startgame, 150);
    lv_obj_set_height(ui_Startgame, 65);
    lv_obj_set_x(ui_Startgame, 130);
    lv_obj_set_y(ui_Startgame, 220);
    lv_obj_set_align(ui_Startgame, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Startgame, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Startgame, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Startgame, lv_color_hex(0xC2A997), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Startgame, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Startgame, lv_color_hex(0x837676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Startgame, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Startgame, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Startgame, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartLabel = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_StartLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_StartLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_StartLabel, 130);
    lv_obj_set_y(ui_StartLabel, 220);
    lv_obj_set_align(ui_StartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartLabel, "Start");
    lv_obj_set_style_text_font(ui_StartLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Pausegame = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Pausegame, 150);
    lv_obj_set_height(ui_Pausegame, 65);
    lv_obj_set_x(ui_Pausegame, 340);
    lv_obj_set_y(ui_Pausegame, 220);
    lv_obj_set_align(ui_Pausegame, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pausegame, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Pausegame, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Pausegame, lv_color_hex(0xC2A997), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pausegame, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Pausegame, lv_color_hex(0x837676), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Pausegame, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Pausegame, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Pausegame, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PauseLabel = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_PauseLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_PauseLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_PauseLabel, 340);
    lv_obj_set_y(ui_PauseLabel, 220);
    lv_obj_set_align(ui_PauseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PauseLabel, "Pause");
    lv_obj_set_style_text_font(ui_PauseLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 初始化贪吃蛇游戏
    init_snake_app();

    lv_obj_add_event_cb(ui_zhuyebtn3, ui_event_zhuyebtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_soundbtn3, ui_event_soundbtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_zhuye3, ui_event_zhuye3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider4, ui_event_Slider4, LV_EVENT_ALL, NULL);
}

void ui_Screen5_screen_destroy(void)
{
    // 清理贪吃蛇游戏资源
    cleanup_snake_app();

    if (ui_Screen5)
        lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Image1 = NULL;
    ui_top_nagivator3 = NULL;
    ui_zhuyebtn3 = NULL;
    ui_WIFIbtn3 = NULL;
    ui_soundbtn3 = NULL;
    ui_blueteethbtn3 = NULL;
    ui_zhuye3 = NULL;
    ui_sound3 = NULL;
    ui_WIFI3 = NULL;
    ui_blueteeth3 = NULL;
    ui_Slider4 = NULL;
    ui_Startgame = NULL;
    ui_StartLabel = NULL;
    ui_Pausegame = NULL;
    ui_PauseLabel = NULL;
}
