// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#ifndef UI_SCREEN7_H
#define UI_SCREEN7_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen7
extern void ui_Screen7_screen_init(void);
extern void ui_Screen7_screen_destroy(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_mainbg1;
extern lv_obj_t * ui_top_nagivator5;
extern void ui_event_zhuyebtn5(lv_event_t * e);
extern lv_obj_t * ui_zhuyebtn5;
extern lv_obj_t * ui_WIFIbtn5;
extern void ui_event_soundbtn5(lv_event_t * e);
extern lv_obj_t * ui_soundbtn5;
extern lv_obj_t * ui_blueteethbtn5;
extern void ui_event_zhuye5(lv_event_t * e);
extern lv_obj_t * ui_zhuye5;
extern lv_obj_t * ui_sound5;
extern lv_obj_t * ui_WIFI5;
extern lv_obj_t * ui_blueteeth5;
extern void ui_event_Slider6(lv_event_t * e);
extern lv_obj_t * ui_Slider6;
extern lv_obj_t * ui_stopmusic;
extern lv_obj_t * ui_playmusic;
extern lv_obj_t * ui_backmusic;
extern lv_obj_t * ui_forwardmusic;
extern void ui_event_stopmusicbtn(lv_event_t * e);
extern lv_obj_t * ui_stopmusicbtn;
extern void ui_event_playmusicbtn(lv_event_t * e);
extern lv_obj_t * ui_playmusicbtn;
extern lv_obj_t * ui_backmusicbtn;
extern lv_obj_t * ui_forwardmusicbtn;
extern lv_obj_t * ui_Dropdownmusic;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

