// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: yueqian_first_project

#ifndef _YUEQIAN_FIRST_PROJECT_UI_H
#define _YUEQIAN_FIRST_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include <sys/types.h>
#include <unistd.h>
#include <sys/wait.h>
#include <dirent.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <stdio.h>
#include <fcntl.h>   
#include <ctype.h> 
#include <time.h>
#include <errno.h>
#include <linux/input.h>
#include <stdbool.h>
#include <signal.h>
#include <pthread.h>  

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"
#include "screens/ui_Screen6.h"
#include "screens/ui_Screen7.h"

///////////////////// VARIABLES ////////////////////


extern lv_anim_t * pangxie_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * zhangyu_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fish1_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fish2_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_main_bg_png);    // assets/main_bg.png
LV_IMG_DECLARE(ui_img_crab_png);    // assets/crab.png
LV_IMG_DECLARE(ui_img_fish_png);    // assets/fish.png
LV_IMG_DECLARE(ui_img_1616326166);    // assets/a-octopusanimal.png
LV_IMG_DECLARE(ui_img_1935761100);    // assets/a-fishanimal3.png
LV_IMG_DECLARE(ui_img_zhuye_png);    // assets/zhuye.png
LV_IMG_DECLARE(ui_img_daohang_png);    // assets/daohang.png
LV_IMG_DECLARE(ui_img_yinle_png);    // assets/yinle.png
LV_IMG_DECLARE(ui_img_shipin_png);    // assets/shipin.png
LV_IMG_DECLARE(ui_img_game_png);    // assets/game.png
LV_IMG_DECLARE(ui_img_yangshengqi_png);    // assets/yangshengqi.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/WIFI.png
LV_IMG_DECLARE(ui_img_lanya_png);    // assets/lanya.png
LV_IMG_DECLARE(ui_img_pic1_png);    // assets/pic1.png
LV_IMG_DECLARE(ui_img_pic2_png);    // assets/pic2.png
LV_IMG_DECLARE(ui_img_pic3_png);    // assets/pic3.png
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_youjiantou_png);    // assets/youjiantou.png
LV_IMG_DECLARE(ui_img_zuojiantou_png);    // assets/zuojiantou.png
LV_IMG_DECLARE(ui_img_zanting_png);    // assets/ai07.png
LV_IMG_DECLARE(ui_img_660221470);    // assets/bg-backward.png
LV_IMG_DECLARE(ui_img_899859302);    // assets/bg-forward.png
LV_IMG_DECLARE(ui_img_bofang_png);    // assets/bofang.png
LV_IMG_DECLARE(ui_img_car1_png);
LV_IMG_DECLARE(ui_img_car2_png);
LV_IMG_DECLARE(ui_img_car3_png);
LV_IMG_DECLARE(ui_img_laba_png);
LV_IMG_DECLARE(ui_img_turnleft_png);
LV_IMG_DECLARE(ui_img_turnright_png);
LV_IMG_DECLARE(ui_img_shuangshan_png);


/* =================== timer ===================*/


/* =================== picture ==================*/

/* =================== video ===================*/




// UI INIT
void ui_init(void);
void ui_destroy(void);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
